version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: brasil_data_hub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-brasil_data_hub}
      POSTGRES_USER: ${POSTGRES_USER:-brasil_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password_here}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - brasil_data_hub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-brasil_user} -d ${POSTGRES_DB:-brasil_data_hub}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Opcional: PgAdmin para interface web de administração
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: brasil_data_hub_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@brasildatahub.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - brasil_data_hub_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  brasil_data_hub_network:
    driver: bridge
